import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from 'next/font/google';
import "./globals.css";
import {ThemeProvider} from "@/providers/theme-provider";
// ** Components
import {SidebarInset, SidebarProvider} from "@/components/ui/sidebar";
import NavBar from "@/components/navigation/NavBar";
import {SideNavBar} from "@/components/navigation/SideNavBar";

const jakarta = Plus_Jakarta_Sans({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-jakarta',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${jakarta.variable}`}
            suppressHydrationWarning
        >
        <body className={`${jakarta.variable} font-sans min-h-full flex flex-col antialiased`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <SidebarProvider>
                <SideNavBar />
                <SidebarInset>
                    <NavBar />
                    <main className="p-4">
                        {children}
                    </main>
                </SidebarInset>
            </SidebarProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}