import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import AppShell from "@/components/layout/AppShell";

const jakarta = Plus_Jakarta_Sans({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-jakarta",
});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Clerk + Next.js App",
    description: "Generated by create next app with Clerk and Sidebar",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider signInUrl="/sign-in" signUpUrl="/sign-up">
            <html
                lang="en"
                className={`${jakarta.variable} ${geistSans.variable} ${geistMono.variable}`}
                suppressHydrationWarning
            >
                <body className="font-sans min-h-full flex flex-col antialiased">
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <AppShell>{children}</AppShell>
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
